{
	'variables': {
		'bin': '<!(node -p "require(\'@node-3d/addon-tools\').getBin()")',
		'qt_core_bin': '<!(node -p "require(\'@node-3d/deps-qmlui\').core.bin")',
		'qt_gui_bin': '<!(node -p "require(\'@node-3d/deps-qmlui\').gui.bin")',
		'qt_qml_bin': '<!(node -p "require(\'@node-3d/deps-qmlui\').qml.bin")',
		'qmlui_include': '<!(node -p "require(\'@node-3d/deps-qmlui\').include")',
		'qmlui_bin': '<!(node -p "require(\'@node-3d/deps-qmlui\').bin")',
	},
	'targets': [
		{
			'target_name': 'qml',
			'includes': ['common.gypi'],
			'sources': [
				'cpp/bindings.cpp',
				'cpp/view.cpp'
			],
			'include_dirs': [
				'<!@(node -e "import(\'@node-3d/addon-tools\').then((m) => m.printInclude())")',
				'<(qmlui_include)',
			],
			'library_dirs': ['<(qmlui_bin)'],
			'conditions': [
				['OS=="linux"', {
					'ldflags': [
						"-Wl,--disable-new-dtags",
						"-Wl,-rpath,'$$ORIGIN:$$ORIGIN/../node_modules/@node-3d/deps-qt-core/<(bin):$$ORIGIN/../node_modules/@node-3d/deps-qt-gui/<(bin):$$ORIGIN/../node_modules/@node-3d/deps-qt-qml/<(bin):$$ORIGIN/../node_modules/@node-3d/deps-qmlui/<(bin):$$ORIGIN/../../@node-3d/deps-qt-core/<(bin):$$ORIGIN/../../@node-3d/deps-qt-gui/<(bin):$$ORIGIN/../../@node-3d/deps-qt-qml/<(bin):$$ORIGIN/../../@node-3d/deps-qmlui/<(bin):$$ORIGIN/../../deps-qt-core/<(bin):$$ORIGIN/../../deps-qt-gui/<(bin):$$ORIGIN/../../deps-qt-qml/<(bin):$$ORIGIN/../../deps-qmlui/<(bin)'",
					],
					'libraries': [
						'-Wl,--no-as-needed',
						'<(qt_core_bin)/libicudata.so.73',
						'<(qt_core_bin)/libicui18n.so.73',
						'<(qt_core_bin)/libicuio.so.73',
						'<(qt_core_bin)/libicutest.so.73',
						'<(qt_core_bin)/libicutu.so.73',
						'<(qt_core_bin)/libicuuc.so.73',
						'<(qt_core_bin)/libQt6Core.so.6',
						'<(qt_core_bin)/libQt6DBus.so.6',
						'<(qt_core_bin)/libQt6Network.so.6',
						'<(qt_gui_bin)/libQt6Gui.so.6',
						'<(qt_gui_bin)/libQt6OpenGL.so.6',
						'<(qt_gui_bin)/libQt6Svg.so.6',
						'<(qt_gui_bin)/libQt6Widgets.so.6',
						'<(qt_gui_bin)/libQt6XcbQpa.so.6',
						'<(qt_gui_bin)/libQt6WaylandClient.so.6',
						'<(qt_gui_bin)/libQt6WaylandEglClientHwIntegration.so.6',
						'<(qt_qml_bin)/libQt6Qml.so.6',
						'<(qt_qml_bin)/libQt6QmlCompiler.so.6',
						'<(qt_qml_bin)/libQt6QmlCore.so.6',
						'<(qt_qml_bin)/libQt6QmlMeta.so.6',
						'<(qt_qml_bin)/libQt6QmlModels.so.6',
						'<(qt_qml_bin)/libQt6QmlWorkerScript.so.6',
						'<(qt_qml_bin)/libQt6Quick.so.6',
						'<(qt_qml_bin)/libQt6QuickControls2.so.6',
						'<(qt_qml_bin)/libQt6QuickControls2Basic.so.6',
						'<(qt_qml_bin)/libQt6QuickControls2BasicStyleImpl.so.6',
						'<(qt_qml_bin)/libQt6QuickControls2Impl.so.6',
						'<(qt_qml_bin)/libQt6QuickDialogs2.so.6',
						'<(qt_qml_bin)/libQt6QuickDialogs2QuickImpl.so.6',
						'<(qt_qml_bin)/libQt6QuickDialogs2Utils.so.6',
						'<(qt_qml_bin)/libQt6QuickEffects.so.6',
						'<(qt_qml_bin)/libQt6QuickLayouts.so.6',
						'<(qt_qml_bin)/libQt6QuickParticles.so.6',
						'<(qt_qml_bin)/libQt6QuickShapes.so.6',
						'<(qt_qml_bin)/libQt6QuickTemplates2.so.6',
						'<(qt_qml_bin)/libQt6QuickVectorImage.so.6',
						'<(qt_qml_bin)/libQt6QuickWidgets.so.6',
						'<(qmlui_bin)/libqmlui.so',
						'-Wl,--as-needed',
					],
				}],
				
				['OS=="mac"', {
					'target_arch': 'arm',
					'libraries': [
						'<(qmlui_bin)/libqmlui.dylib',
						'-Wl,-rpath,@loader_path',
						'-Wl,-rpath,@loader_path/../node_modules/@node-3d/deps-qt-core/<(bin)',
						'-Wl,-rpath,@loader_path/../node_modules/@node-3d/deps-qt-gui/<(bin)',
						'-Wl,-rpath,@loader_path/../node_modules/@node-3d/deps-qt-qml/<(bin)',
						'-Wl,-rpath,@loader_path/../node_modules/@node-3d/deps-qmlui/<(bin)',
						'-Wl,-rpath,@loader_path/../../@node-3d/deps-qt-core/<(bin)',
						'-Wl,-rpath,@loader_path/../../@node-3d/deps-qt-gui/<(bin)',
						'-Wl,-rpath,@loader_path/../../@node-3d/deps-qt-qml/<(bin)',
						'-Wl,-rpath,@loader_path/../../@node-3d/deps-qmlui/<(bin)',
						'-Wl,-rpath,@loader_path/../../deps-qt-core/<(bin)',
						'-Wl,-rpath,@loader_path/../../deps-qt-gui/<(bin)',
						'-Wl,-rpath,@loader_path/../../deps-qt-qml/<(bin)',
						'-Wl,-rpath,@loader_path/../../deps-qmlui/<(bin)',
					],
				}],
				
				['OS=="win"', {
					'libraries': ['-lqmlui'],
				}],
				
			],
		},
	]
}
