name: Test
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Tests (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: windows-x64
            os: windows-2022
            node_arch: x64
            archflags: ''
          - target: linux-x64
            os: ubuntu-22.04
            node_arch: x64
            archflags: ''
          - target: linux-arm64
            os: ubuntu-24.04-arm
            node_arch: arm64
            archflags: ''
          - target: darwin-x64
            os: macos-15-intel
            node_arch: x64
            archflags: '-arch x86_64'
          - target: darwin-arm64
            os: macos-15
            node_arch: arm64
            archflags: '-arch arm64'

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          architecture: ${{ matrix.node_arch }}
          cache: 'npm'

      - name: Print Native Target
        run: |
          echo "runner=$(uname -s)-$(uname -m)"
          node -p "'node=' + process.version + ' platform=' + process.platform + ' arch=' + process.arch"
          npm config get arch

      - name: Install Modules
        run: npm ci --ignore-scripts

      - name: Install Dependency Binaries
        run: npm rebuild @node-3d/deps-qt-core @node-3d/deps-qt-gui @node-3d/deps-qt-qml @node-3d/deps-qmlui @node-3d/segfault

      - name: Build Current Binary
        run: npm run build:rebuild
        env:
          npm_config_arch: ${{ matrix.node_arch }}
          ARCHFLAGS: ${{ matrix.archflags }}

      - name: Run Unit Tests - Linux
        if: matrix.target == 'linux-x64'
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq libgles2-mesa-dev libxcb-cursor0 libxcb-icccm4 libxcb-keysyms1 libxcb-shape0 libxcb-xkb1 libxkbcommon-x11-0
          xvfb-run --auto-servernum npm run test:ci

      # - name: Run Unit Tests - MacOS
      #   if: matrix.target == 'darwin-arm64'
      #   run: npm run test:ci
